name: Build and deploy new MQTT container

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build --build-arg MOSQUITTO_USER=${{ secrets.MOSQUITTO_USER }} --build-arg MOSQUITTO_PASSWORD=${{ secrets.MOSQUITTO_PASSWORD }} -f mqtt.Dockerfile -t ghcr.io/condocam/mqtt:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/condocam/mqtt:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH to server and run Docker Compose
        env:
          DOCKER_IMAGE: "ghcr.io/condocam/mqtt:latest"
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/streamserver
            docker compose up -d --build mqtt
          EOF
